### ISSUE TITLE
Intentions: Give 'Unused AMD' precendence over 'Mismatch'

### ISSUE THREAD

**Issue by speich** [cefolger/needsmoredojo#151]
Currently if you have an unused AMD import, which is also a 'Mismatch between define and parameter' the module gets colored red, but not crossed through. Imho, it should either be both red and crossed through or only crossed through, because if it's unused you are going to remove it anyway, so Mismatch (red) is kinda irrelevant.

**Comment by cefolger** [comment]
It may be a limitation of inspections, but it's worth a look at least. Thanks for reporting this.

**Comment by cefolger** [comment]
After investigating this more, I'm going to keep the current behavior. The reason is that if something is flagged as mismatched it could be either a) the literal/parameter names are mismatched or b) the imports are out of order / not lining up. 

In the case of b), this means some of the imports would be incorrectly flagged as unused. I'd prefer keeping the current behavior instead of incorrectly marking them unused. 

I'll put it in the TBD pile though in case a better solution comes up.

**Comment by speich** [comment]
On Dienstag, 4. Februar 2014 03:35:53, cefolger wrote:

> After investigating this more, I'm going to keep the current behavior.
> The reason is that if something is flagged as mismatched it could be
> either a) the literal/parameter names are mismatched or b) the imports
> are out of order / not lining up.
> 
> In the case of b), this means some of the imports would be incorrectly
> flagged as unused. I'd prefer keeping the current behavior instead of
> incorrectly marking them unused.
> 
> I'll put it in the TBD pile though in case a better solution comes up.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cefolger/needsmoredojo/issues/151#issuecomment-34025300.

ok, thanks for checking.

**Comment by cefolger** [comment]
It turns out that after fixing #162 this is also fixed.
